#!/usr/bin/env python3
"""
Quickelt Environment File Writer
================================

Centralized .env file read/write operations. Eliminates the duplicated
env metadata update logic previously scattered across provisioners.
"""

import logging
import os
from pathlib import Path


class EnvWriter:
    _DEFAULT_AZURE_RESOURCE_GROUP = "quickelt-rg"
    _DEFAULT_AZURE_LOCATION = "eastus"

    def __init__(self, env_path: Path, logger: logging.Logger | None = None):
        self.env_path = env_path
        self.log = logger or logging.getLogger("quickelt.env")

    def write(self, cloud: str, storage: dict, compute: dict, dw: dict) -> None:
        existing_lines: list[str] = []
        try:
            with open(self.env_path) as f:
                existing_lines = f.readlines()
        except OSError:
            pass

        wizard_keys: dict[str, str] = {
            "CLOUD_PROVIDER": cloud,
        }

        if cloud == "AWS":
            wizard_keys["AWS_S3_BUCKET"] = storage["name"]
        else:
            wizard_keys["AZURE_STORAGE_ACCOUNT"] = storage["name"]
            wizard_keys["AZURE_RESOURCE_GROUP"] = self._DEFAULT_AZURE_RESOURCE_GROUP
            wizard_keys["AZURE_LOCATION"] = self._DEFAULT_AZURE_LOCATION

        if storage["layers"]:
            wizard_keys["STORAGE_LAYERS"] = ",".join(storage["layers"])
        else:
            wizard_keys["STORAGE_LAYERS"] = ""

        wizard_keys["COMPUTE_TYPE"] = compute["compute"]
        wizard_keys["BOOTSTRAP_VM"] = str(compute["bootstrap_vm"]).lower()

        if dw.get("gold_external_db"):
            wizard_keys["INSTALL_LOCAL_POSTGRES"] = str(dw.get("install_local_postgres", False)).lower()
            wizard_keys["DW_HOST"] = dw.get("dw_host", "")
            wizard_keys["DW_PORT"] = dw.get("dw_port", "5432")
            wizard_keys["DW_DATABASE"] = dw.get("dw_database", "quickelt_db")
            wizard_keys["DW_USERNAME"] = dw.get("dw_username", "quickelt")
            wizard_keys["DW_PASSWORD"] = dw.get("dw_password", "")
            wizard_keys["PG_STRATEGY"] = dw.get("pg_strategy", "")
            if dw.get("managed_cloud_choice"):
                wizard_keys["MANAGED_CLOUD_CHOICE"] = dw["managed_cloud_choice"]

        updated_keys: set[str] = set()
        new_lines: list[str] = [
            "# Quickelt Infrastructure Configuration\n",
            "# Generated by infrastructure/setup.py\n",
            "\n",
        ]

        for line in existing_lines:
            stripped = line.strip()
            if "=" in stripped and not stripped.startswith("#"):
                key = stripped.split("=", 1)[0].strip()
                if key in wizard_keys:
                    new_lines.append(f"{key}={wizard_keys[key]}\n")
                    updated_keys.add(key)
                    continue
            new_lines.append(line)

        for key, value in wizard_keys.items():
            if key not in updated_keys:
                new_lines.append(f"{key}={value}\n")

        new_lines.append("\n")

        try:
            with open(self.env_path, "w") as f:
                f.writelines(new_lines)
            if dw.get("gold_external_db"):
                self._restrict_permissions()
            self.log.info("Configuration written to %s", self.env_path)
        except OSError as exc:
            self.log.error("Could not write .env file: %s", exc)
            raise SystemExit(1) from exc

    def update_metadata(self, metadata: dict[str, str]) -> None:
        existing_lines: list[str] = []
        try:
            with open(self.env_path) as f:
                existing_lines = f.readlines()
        except OSError:
            pass

        updated_keys: set[str] = set()
        new_lines: list[str] = []

        for line in existing_lines:
            stripped = line.strip()
            if "=" in stripped and not stripped.startswith("#"):
                key = stripped.split("=", 1)[0].strip()
                if key in metadata:
                    new_lines.append(f"{key}={metadata[key]}\n")
                    updated_keys.add(key)
                    continue
            new_lines.append(line)

        for key, value in metadata.items():
            if key not in updated_keys:
                new_lines.append(f"{key}={value}\n")

        try:
            with open(self.env_path, "w") as f:
                f.writelines(new_lines)
            self.log.debug("Updated .env with %d metadata keys", len(metadata))
        except OSError as exc:
            self.log.warning("Could not update .env with metadata: %s", exc)

    def read_value(self, key: str) -> str | None:
        try:
            with open(self.env_path) as f:
                for line in f:
                    stripped = line.strip()
                    if stripped.startswith(f"{key}="):
                        return stripped.split("=", 1)[1].strip()
        except OSError:
            pass
        return None

    def _restrict_permissions(self) -> None:
        try:
            os.chmod(self.env_path, 0o600)
        except OSError:
            self.log.debug("Could not set restrictive permissions on .env file")
